
---
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    name: manager-role
  rules:
  - apiGroups:
    - projectedresource.storage.openshift.io
    resources:
    - shares
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - projectedresource.storage.openshift.io
    resources:
    - shares/finalizers
    verbs:
    - update
  - apiGroups:
    - projectedresource.storage.openshift.io
    resources:
    - shares/status
    verbs:
    - get
    - patch
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: projected-resource-secret-configmap-share-watch-sar-create
  rules:
    - apiGroups:
        - ""
      resources:
        - secrets
        - configmaps
        - pods
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - projectedresource.storage.openshift.io
      resources:
        - shares
      verbs:
        - get
        - list
        - watch
    - apiGroups:
      - authorization.k8s.io
      resources:
        - subjectaccessreviews
      verbs:
        - create