# permissions for end users to view shares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: share-viewer-role
rules:
- apiGroups:
  - projectedresource.storage.openshift.io
  resources:
  - shares
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - projectedresource.storage.openshift.io
  resources:
  - shares/status
  verbs:
  - get
